sudo: required
services:
  - docker

before_install:
  - docker build -t dharmeshchavda/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dharmeshchavda/react-test npm test -- --coverage

after_success:
  - docker build -t dharmeshchavda/multi-client ./client
  - docker build -t dharmeshchavda/multi-nginx ./nginx
  - docker build -t dharmeshchavda/multi-server ./server
  - docker build -t dharmeshchavda/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dharmeshchavda/multi-client
  - docker push dharmeshchavda/multi-nginx
  - docker push dharmeshchavda/multi-server
  - docker push dharmeshchavda/multi-worker

deploy: 
  provider: elasticbeanstalk
  reggion: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-038108488836
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrte_access_key:
    secure: $AWS_SECRTE_KEY